### ISSUE TITLE
map[string]interface 转换有问题

### ISSUE THREAD

**Issue by preakrel** [ctfang/http_build_query#1]
data :=map[string]interface {}{
  "id": 1.0,
  "name": "john",
  "sub": map[string]interface {}{
    "0": map[string]interface {}{
      "1": map[string]interface {}{
        "2": 1.0,
      },
    },
    "1": 3.0,
    "2": "three",
  },
}
这种格式转换出来有问题：id=1&name=john&sub[0][1][2]=1&sub[0][1]=3&sub[0][2]=three

应该是id=1&name=john&sub[0][1][2]=1&sub[1]=3&sub[2]=three 才对

**Comment by ctfang** [comment]
已修复, 你更新试试

**Comment by ctfang** [comment]
已修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 琉璃 ***@***.***&gt;
发送时间: 2022年5月19日 16:29
收件人: ctfang/http_build_query ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ctfang/http_build_query] map[string]interface 转换有问题 (Issue #1)





 
data :=map[string]interface {}{
 "id": 1.0,
 "name": "john",
 "sub": map[string]interface {}{
 "0": map[string]interface {}{
 "1": map[string]interface {}{
 "2": 1.0,
 },
 },
 "1": 3.0,
 "2": "three",
 },
 }
 这种格式转换出来有问题：id=1&amp;name=john&amp;sub[0][1][2]=1&amp;sub[0][1]=3&amp;sub[0][2]=three
 
应该是id=1&amp;name=john&amp;sub[0][1][2]=1&amp;sub[1]=3&amp;sub[2]=three 才对
